

field_types = {
    'item_name': 'string',
    'item_type': 'string',
    'unique_id': 'Int64',
    'item_name_rp': 'string',
    'item_type_rp': 'string',
    'git_rp': 'bool',
    'item_name_hm': 'string',
    'item_type_hm': 'string',
    'item_name_hm_db': 'string',
    'item_type_hm_db': 'string',
    'item_name_rp_db': 'string',
    'item_type_rp_db': 'string',
    'item_name_rp_di': 'string',
    'item_type_rp_di': 'string',
    'item_name_hm_di': 'string',
    'item_type_hm_di': 'string',
    'dot_struc_di': 'string',
    'cat_1_di': 'string',
    'cat_1_name_di': 'string',
    'cat_2_di': 'string',
    'comment_di': 'string',
    'no_show_di': 'bool',
    'sort_orig': 'Int64',
    'unique_id_rp': 'Int64',
    'unique_id_db': 'Int64',
    'unique_id_hm': 'Int64',
    'unique_id_di': 'Int64',
    'item_name_home': 'string',
    'item_type_home': 'string',
    'item_name_repo': 'string',
    'item_type_repo': 'string',
    'dot_struc': 'string',
    'st_alert': 'string',
    'st_db_all': 'string',
    'st_docs': 'string',
    'st_misc': 'string',
    'sort_out': 'Int64'
}